### ISSUE TITLE
Unicode Error in MacOSX

### ISSUE THREAD

**Issue by sharmaa9** [PharmGKB/PGxPOP#1]
Hi, 

I am currently trying to use PGxPOP for haplotyping the UKBIOBANK'S VCF files (v4.2, ascii). I installed PGxPOP on my MAC using the list of commands given in an environment created with conda using python 3.6. However, when testing this software with the test data (that you have on your page: VcfReaderTest-phasing.vcf), PGxPOP throws this error- 

 File "/Users/sharmaa9/Desktop/Conda/envs/python3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

I also tried using "PYTHONIOENCODING=UTF-8". But it still fails. 

Also, just for your information, I am using the following command-
python bin/PGxPOP.py --vcf /Users/sharmaa9/Desktop/PGx/PGXPOP/PGxPOP/test_vcf.vcf.gz.tbi -g CYP2D6 --phased --build grch38 -o test_new.txt

For my own dataset, I used Eagle to first phase the file and then ran PGxPOP (after bgziping and tabixing) which throws the same error.

I apologize if this question is naive, but I am new to the world of population genetics as well as programming.

I truly appreciate your help.

Thanks

**Comment by alavertu** [comment]
Hi @sharmaa9,

Can you try pointing the --vcf path to the vcf and not the tabix index file? 

Would be the following command instead:
> python bin/PGxPOP.py --vcf /Users/sharmaa9/Desktop/PGx/PGXPOP/PGxPOP/test_vcf.vcf.gz -g CYP2D6 --phased --build grch38 -o test_new.txt

**Comment by sharmaa9** [comment]
Thanks for your response.
So I try that and i get this error-

File "/Users/sharmaa9/Desktop/PGx/PGXPOP/PGxPOP/PGxPOP/bin/DawgToys.py", line 320, in fetch_genotypes
    records = tb.query("%s" % chr, position-1, position+1)
tabix.TabixError: query failed

Thanks,
Anu

**Comment by alavertu** [comment]
Hi Anu,

Sorry to hear that didn't work. Can you give me a little more information? 

What do the top few lines of your VCF look like after the column header? I'd like to see how chromosome names are formatted, as this sometimes differs among VCFs.  

Have you successfully tabix query'd this file outside of PGxPOP?

Are all the chromosomes present in the file?

**Comment by sharmaa9** [comment]
Thanks Alan, 

Really appreciate your help. Actually, I am trying this with your example data file "VcfReaderTest-phasing.vcf". I bgzipped it and then tabixed it and now running PGxPOP on it.

**Comment by alavertu** [comment]
Hi Anu,

Sorry, that test file doesn't contain CYP2D6. Can you try running:
> python bin/PGxPOP.py --vcf /Users/sharmaa9/Desktop/PGx/PGXPOP/PGxPOP/test_vcf.vcf.gz -g DPYD --phased --build grch38 -o test_new.txt

**Comment by sharmaa9** [comment]
Hi Adam,

Got it! Its working! :) thanks so much for your help! Really appreciate your time. 
And thanks for coding this tool. Also, I am just starting in this field so I might bug you again in near future with queries.

Best,
Anu

**Comment by alavertu** [comment]
Glad to hear its working and welcome to the field, it's a good one :)
