### ISSUE TITLE
Recommendation for updated allele definitions?

### ISSUE THREAD

**Issue by AlePilHen** [PharmGKB/PGxPOP#15]
Hello

First of all thank you for `PGxPOP`, it has made my work much easier!

Now, that it is not being actively maintained do you have any suggestions for how to keep using `PGxPOP` but with updated allele definitions from PharmVar or PharmGKB?
Perhaps there is a script that can convert PharmGKB variant tables into allele definition `.json` files ?
Or is the solution to use PharmCat instead?

Any help is much appreciated. 
Thank you!
- Alexander

**Comment by markwoon** [comment]
The solution is to use PharmCAT instead.
